export default {
  "index": "Introduction",
  "scope": "1. Scope",
  "conformance": "2. Conformance",
  "normative-references": "3. Normative References",
  "overview": "4. Overview",
  "notational-conventions": "5. Notational Conventions",
  "ecmascript-data-types-and-values": "6. ECMAScript Data Types and Values",
  "abstract-operations": "7. Abstract Operations",
  "syntax-directed-operations": "8. Syntax-Directed Operations",
  "executable-code-and-execution-contexts": "9. Executable Code and Execution Contexts",
  "ordinary-and-exotic-objects-behaviours": "10. Ordinary and Exotic Objects Behaviours",
  "ecmascript-language-source-code": "11. ECMAScript Language: Source Text",
  "ecmascript-language-lexical-grammar": "12. ECMAScript Language: Lexical Grammar",
  "ecmascript-language-expressions": "13. ECMAScript Language: Expressions",
  "ecmascript-language-statements-and-declarations": "14. ECMAScript Language: Statements and Declarations",
  "ecmascript-language-functions-and-classes": "15. ECMAScript Language: Functions and Classes",
  "ecmascript-language-scripts-and-modules": "16. ECMAScript Language: Scripts and Modules",
  "error-handling-and-language-extensions": "17. Error Handling and Language Extensions",
  "ecmascript-standard-built-in-objects": "18. ECMAScript Standard Built-in Objects",
  "global-object": "19. The Global Object",
  "fundamental-objects": "20. Fundamental Objects",
  "numbers-and-dates": "21. Numbers and Dates",
  "text-processing": "22. Text Processing",
  "indexed-collections": "23. Indexed Collections",
  "keyed-collections": "24. Keyed Collections",
  "structured-data": "25. Structured Data",
  "managing-memory": "26. Managing Memory",
  "control-abstraction-objects": "27. Control Abstraction Objects",
  "reflection": "28. Reflection",
  "memory-model": "29. Memory Model",
  "grammar-summary": "Annex: Grammar Summary",
  "additional-ecmascript-features-for-web-browsers": "Annex: Additional ECMAScript Features for Web Browsers",
  "strict-mode-of-ecmascript": "Annex: The Strict Mode of ECMAScript",
  "host-layering-points": "Annex: Host Layering Points",
  "corrections-and-clarifications-in-ecmascript-2015-with-possible-compatibility-impact": "Annex: Corrections and Clarifications in ECMAScript 2015 with Possible Compatibility Impact",
  "additions-and-changes-that-introduce-incompatibilities-with-prior-editions": "Annex: Additions and Changes That Introduce Incompatibilities with Prior Editions",
  "bibliography": "Annex: Bibliography",
  "colophon": "Annex: Colophon"
}
